# Generated by Django 5.0.3 on 2024-03-28 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blockchain', models.CharField(choices=[('ETHEREUM', 'Ethereum'), ('SOLANA', 'Solana'), ('BSC', 'BNB'), ('MANTA', 'Manta'), ('POLYGON', 'Polygon'), ('ARBITRUM', 'Arbitrum'), ('AVALANCHE', 'Avalanche'), ('FANTOM', 'Fantom'), ('HECO', 'Heco'), ('OKEX', 'OKEx')], default='ETHEREUM', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('market_cap', models.CharField(max_length=100)),
                ('circulating_supply', models.IntegerField()),
                ('max_supply', models.IntegerField()),
                ('official_url', models.URLField()),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_data.blockchain')),
            ],
        ),
    ]
