# Generated by Django 5.0.3 on 2024-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
